---
title: "Interactive map"
author: "Joonas Siivonen"
date: "7/31/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(XML)
library(leaflet)
```

## Interactive map: Locations of 10 most powerful supercomputers 
This page was created on `r date()` GMT+03

```{r preprocessing, echo=FALSE}
#read the data 
supercomputers <- xmlToDataFrame("TOP500_201706_all.xml")
#select columns that will be used & rename for easy handling
top10computers <- supercomputers[c(1:10),c(1,2,3,13,15)]
     

#add the coordinates
lat <-c(31.550946,23.070361,46.024636, 35.931262, 37.690183, 37.875395, 35.712895, 34.653654, 41.718512,35.844319)
lng <- c(120.254641, 113.394787,8.960065, -84.309660, -121.693352, -122.253252, 139.761968, 135.220445,-87.978561, -106.287141)

top10computers$long <-lng
top10computers$lat <- lat
colnames(top10computers)<- c("rank", "system-id", "name", "town", "country", "long", "lat")   
```


```{r map, echo=FALSE}
leaflet(top10computers) %>% addTiles() %>% addMarkers(lng=top10computers$long, lat=top10computers$lat, label=top10computers$name)

```

source:
https://www.top500.org/lists/2017/06/